// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0x_qeAYYnX01Tgv0vBJN1iXHNubByf0w',
    appId: '1:513024927801:web:b8bdf49ff1fc6cb8e9c5e8',
    messagingSenderId: '513024927801',
    projectId: 'chatapp-3acd9',
    authDomain: 'chatapp-3acd9.firebaseapp.com',
    storageBucket: 'chatapp-3acd9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhq6F4PxO9IlA2U901OwgM5q-wf6_jFgA',
    appId: '1:513024927801:android:db05c7d7db6137d0e9c5e8',
    messagingSenderId: '513024927801',
    projectId: 'chatapp-3acd9',
    storageBucket: 'chatapp-3acd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhD3N1d56q5ISUyCCJ0BiguLPrnstzvVM',
    appId: '1:513024927801:ios:c35bc34021acfd54e9c5e8',
    messagingSenderId: '513024927801',
    projectId: 'chatapp-3acd9',
    storageBucket: 'chatapp-3acd9.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhD3N1d56q5ISUyCCJ0BiguLPrnstzvVM',
    appId: '1:513024927801:ios:acd8cf17520fe4d2e9c5e8',
    messagingSenderId: '513024927801',
    projectId: 'chatapp-3acd9',
    storageBucket: 'chatapp-3acd9.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
